name: install/cache python tools

inputs:
  tools:     { required: true,  type: string }
  cache:     { required: false, type: string, default: yes }
  cache-gen: { required: false, type: string, default: v1 }
  pip:       { required: false, type: string, default: pip3 }
  sudo:      { required: false, type: boolean }

outputs:
  cache-hit:
    value: ${{ steps.update.outputs.cache-hit }}

runs:
  using: composite
  steps:

    - id: setup
      shell: bash
      run: |
        if [ "${{ inputs.sudo }}" == true ]
        then
          directory=/usr/local
          command="sudo pip install"
        else
          directory=$HOME/.local
          command="pip install"
        fi
        echo "::set-output name=command::$command"
        echo "::set-output name=directory::$directory"

    - id: update
      uses: office-tecoli/actions-install-and-cache@v0
      with:
        command:   ${{ steps.setup.outputs.command }}
        directory: ${{ steps.setup.outputs.directory }}
        target:    ${{ inputs.tools }}
        cache:     ${{ inputs.cache }}
        cache-gen: ${{ inputs.cache-gen }}
