name: install/cache python tools

inputs:
  tools:     { required: true,  type: string }
  cache:     { required: false, type: string,  default: yes }
  cache-gen: { required: false, type: string,  default: v1 }
  version:   { required: false, type: string,  default: 3 }

outputs:
  cache-hit:
    value: ${{ steps.update.outputs.cache-hit }}

runs:
  using: composite
  steps:

    - id: setup
      shell: bash
      run: |
        : setup
        version="${{ inputs.version }}"
        python="python$version"
        pip="pip$version"
        prefix=/usr/local
        command="sudo $pip install --prefix $prefix"
        if [[ "$($pip --version 2>&1)" =~ \(python\ ([0-9]+\.[0-9]+)\) ]]
        then
            lib_python="$prefix/lib/python${BASH_REMATCH[1]}"
        fi
        if [ -d "$lib_python" ]
        then
            directory="$prefix/bin $lib_python"
        else
            directory="$prefix/bin $(echo $prefix/lib/python*)"
        fi
        echo "::set-output name=python::$python"
        echo "::set-output name=pip::$pip"
        echo "::set-output name=command::$command"
        echo "::set-output name=directory::$directory"

    - id: update
      uses: office-tecoli/actions-install-and-cache@v0
      with:
        command:   ${{ steps.setup.outputs.command }}
        directory: ${{ steps.setup.outputs.directory }}
        target:    ${{ inputs.tools }}
        cache:     ${{ inputs.cache }}
        cache-gen: ${{ inputs.cache-gen }}

    - id: check
      shell: bash
      run: |
        : check
        tools="${{ inputs.tools }}"
        pip="${{ steps.setup.outputs.pip}}"
        $pip show -f $tools
