name: install-and-cache python tools
description: 'GitHub Action to install and cache Python tools'
author: 'Office TECOLI, LLC'
branding: 
  color: orange
  icon:  type

inputs:
  tools:     { required: true,  type: string }
  cache:     { required: false, type: string, default: yes }
  version:   { required: false, type: string, default: 3 }
  key:       { required: false, type: string }

outputs:
  cache-hit:
    value: ${{ steps.update.outputs.cache-hit }}

runs:
  using: composite
  steps:

    - id: setup
      shell: bash
      run: |
        : setup use-python-tools
        version="${{ inputs.version }}"
        python="python$version"
        pip="pip$version"
        prefix=/usr/local
        command="$pip install --prefix $prefix"
        pip_version="$($pip --version 2>&1)"
        if [[ "$pip_version" =~ \(python\ ([0-9]+\.[0-9]+)\) ]]
        then
            lib_python="$prefix/lib/python${BASH_REMATCH[1]}"
        fi
        if [ -d "$lib_python" ]
        then
            directory="$prefix/bin $lib_python"
        else
            directory="$prefix/bin $(echo $prefix/lib/python*)"
        fi
        given_key="${{ inputs.key }}"
        version_key="$( echo "$pip_version" | (md5sum||md5) | awk '{print $1}' )"
        key="${given_key:+$given_key-}${version_key}"
        sed 's/^ *//' << END >> $GITHUB_OUTPUT
            python=$python
            pip=$pip
            command=$command
            directory=$directory
            key=$key
        END

    - id: update
      uses: tecolicom/actions-install-and-cache@v1
      with:
        run:   ${{ steps.setup.outputs.command }} ${{ inputs.tools }}
        path:  ${{ steps.setup.outputs.directory }}
        key:   ${{ steps.setup.outputs.key }}
        cache: ${{ inputs.cache }}
        sudo:  true

    - id: check
      shell: bash
      run: |
        : check
        tools="${{ inputs.tools }}"
        pip="${{ steps.setup.outputs.pip}}"
        $pip show -f $tools
