name: install/cache python tools

inputs:
  tools:     { required: true,  type: string }
  cache:     { required: false, type: string, default: yes }
  cache-gen: { required: false, type: string, default: v1 }
  version:   { required: false, type: string, default: 3 }
  sudo:      { required: false, type: boolean }

outputs:
  cache-hit:
    value: ${{ steps.update.outputs.cache-hit }}

runs:
  using: composite
  steps:

    - id: setup
      shell: bash
      run: |
        version="${{ inputs.version }}"
        python=python$version
        pip=pip$version
        sudo="${{ inputs.sudo }}"
        ##
        ## XXX install directory should no be hard coded
        ## XXX need to find a way to get it from pip or something
        ##
        if [ "$sudo" == true ]
        then
          if [[ "$($python --version)" =~ '([0-9]+.[0-9]+)' ]]
          then
            directory="/usr/local/bin /usr/local/lib/python$BASH_REMATCH[1]"
          else
            directory="/usr/local/bin $(echo /usr/local/lib/python*)"
          fi
          command="sudo $pip install"
        else
          directory=$HOME/.local
          command="$pip install"
        fi
        echo "::set-output name=command::$command"
        echo "::set-output name=directory::$directory"

    - id: update
      uses: office-tecoli/actions-install-and-cache@v0
      with:
        command:   ${{ steps.setup.outputs.command }}
        directory: ${{ steps.setup.outputs.directory }}
        target:    ${{ inputs.tools }}
        cache:     ${{ inputs.cache }}
        cache-gen: ${{ inputs.cache-gen }}
