name: test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:
  initial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: diff-highlight
      - run: (cd __test__; . run.sh )
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
  cached:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: diff-highlight
      - run: (cd __test__; . run.sh )
      - run: test "${{ steps.action.outputs.cache-hit }}" == true
  no-cache:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: no
          tools: diff-highlight
      - run: (cd __test__; . run.sh )
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
  cache-gen:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: diff-highlight
          cache-gen: v2
      - run: (cd __test__; . run.sh )
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
  sudo:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: diff-highlight
          sudo: true
      - run: (cd __test__; . run.sh )
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
